name: whispin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #UI/UX
  google_fonts: 6.3.2

  # Firebase 系パッケージ（互換性を考慮）
  firebase_core: 4.2.1
  firebase_auth: 6.1.2
  cloud_firestore: 6.1.0

  #Utilities
  http: 1.6.0
  crypto: 3.0.3
  shared_preferences: 2.2.2
  intl: 0.19.0

  # Other
  image_picker: 1.2.1
  provider: 6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true