name: backend
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.3
  firebase_admin: ^0.2.0   # Firebase Admin SDK for Dart（サーバー用）
  mailer: ^6.0.0
  crypto: ^3.0.3
  googleapis: any
  googleapis_auth: any

